### ISSUE TITLE
copyright infringement

### ISSUE THREAD

**Issue by fab4U** [blinkenrocket/webedit#1]
Hallo Muzy!
Der Webeditor verwendet zur Vorschau den Zeichensatz des Hacklace2. Dies stellt ebenfalls eine Verletzung des Urheberrechts dar.
Bitte setze dich umgehend mit mir in Verbindung, um diese sehr unschöne Sache zu bereinigen.
Viele Grüße
Frank

**Comment by muzy** [comment]
siehe andere Diskussion

**Comment by muzy** [comment]
Font wurde gelöscht
